export const schools = [
  {
    name: "Ecole du Sacré-Cœur de Lindthout",
    desc: "Primary school",
    lat: 50.8392135,
    long: 4.4035579,
    url: "../../photos/school.jpeg",
    contact: "https://www.montessoribrussels.org/",
    funding: "Public",
    age: "6 to 9 y.o",
    review: 3,
    lang: "French",
  },
  {
    name: "Montessori",
    desc: "Primary school",
    lat: 50.8366073,
    long: 4.4058246,
    url: "../../photos/montessori.jpeg",
    contact: "https://www.montessoribrussels.org/",
    funding: "Public",
    age: "6 to 9 y.o",
    review: 3,
    lang: "French",
  },
];